name: 9.0
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coq-community/docker-coq-action@v1.5.2
      with:
        coq_version: "9.0"
        ocaml_version: default
        before_script: |
          startGroup "Workaround permission issue"
            sudo chown -R coq:coq .
          endGroup
        script: |
          startGroup "Build project"
            make
          endGroup
        after_script: |
          startGroup "Revert permissions"
            sudo chown -R 1001:116 .
          endGroup
